### ISSUE TITLE
Dashboard not updated

### ISSUE THREAD

**Issue by nikosdouv** [squaredev-io/GFM-UAT#18]
I had a couple of accounts linked 
Then I added more accounts in My wallet
Transactions of the said accounts are displayed ok 
But the dashboard still shows the previous picture. It was not updated with the new data from the added accounts

**Comment by chris-iliopoulos** [comment]
If we're talking about the cashflow graph in the Dashboard then it's natural because it will be updated on the next cashflow cron job run (which is something we manage time-wise). That being said we could open a UX issue and add an info message or something similar to let the user know in such cases. @ksiabani ?

**Comment by ksiabani** [comment]
Yes, I agree, we need something there to let the user know the data is not updated.

**Comment by awareness481** [comment]
Won't be fixed immediately but it's something that certainly needs to change, thanks for the report.

**Comment by chris-iliopoulos** [comment]
Another finding with this issue is that: Hitting the Dashboard url doesn’t call all required APIs (e.g. cashflow) which leads to outdated information. This happens in addition with the above

**Comment by chris-iliopoulos** [comment]
Closing this for now because the only thing that doesn't exist is a UX thing to let the user know that the new bank info are being processed.
