### ISSUE TITLE
Card transactions appear twice (Alpha Bank)

### ISSUE THREAD

**Issue by GeorgeVarvates** [squaredev-io/GFM-UAT#87]
![image](https://user-images.githubusercontent.com/64831585/186665191-48ddbc43-f01d-4e1b-bd3b-0895fd16fd7a.png)
It's the same payment. I guess the bottom comes from the card and the top comes from the account transactions

**Comment by chris-iliopoulos** [comment]
It probably is ... if you open the transactions details you will understand better which is which. This is an ongoing problem that we are investigating because not all banks respond in the same manner with accounts and cards unfortunately so we have to come up with a solution. Will close this issue because it's being tracked here: https://github.com/squaredev-io/GFM-UAT/issues/71
