### ISSUE TITLE
Cash Withdrawal Category

### ISSUE THREAD

**Issue by sinnec** [squaredev-io/GFM-UAT#91]
There's something way off with Cash withdrawal category. Below it shows entertainment but on another transaction shows health:

<img width="911" alt="Screenshot 2022-08-29 at 12 56 57" src="https://user-images.githubusercontent.com/48223149/187176573-48015a3b-a690-48c5-bba0-0b052cfc914d.png">

**Comment by chris-iliopoulos** [comment]
@stavrostheocharis can you please confirm that this is a problem of WYRE and whether it can be fixed or not.

**Comment by stavrostheocharis** [comment]
Is it exactly the same description in both transactions and coming from the same bank?

If yes, maybe the one is coming from the card and the other from the account (Since S1 in Piraeus sends them both). 
Since there exist 2 pipelines in Wyre one for the cards and one for the accounts and currently Wyre "does not know to connect them for Pireaus" it produces 2 different results (not 100% that this is the issue). Probably it is connected with the duplicated transactions open issue for Eurobank, Pireaus.

**Comment by sinnec** [comment]
No, it's different transactions but same day, same account, same bank. The description is way off lately.

<img width="869" alt="Screenshot 2022-09-05 at 11 49 41" src="https://user-images.githubusercontent.com/48223149/188409002-fea61431-9112-4600-b692-3a7564a2243e.png">

**Comment by stavrostheocharis** [comment]
So in this case, it is just the prediction of Wyre. It seems that based on the trained data transactions, it looks similar to these categories (per each one of them). I believe that the confidence score will be low.

Currently, we cannot do anything about it. (In the future if we have mcc codes it will be 100% accurate)

**Comment by chris-iliopoulos** [comment]
Closing this as there's no action to be taken atm
