### ISSUE TITLE
AFOROLOGITO 

### ISSUE THREAD

**Issue by nikosdouv** [squaredev-io/GFM-UAT#94]
1. Although i have several transactions from various categories, the main screen does not display them correctly. I attach the main screen which shows the clasification of my transactions. Nowhere near reality. Example: I have a transaction in category Insurance/Pension but the main screen does not show any transaction in this category. Nevertheless, in BUDGET page displays the expense category correctly. 
2. We were expecting that there should be a correlation between the categories of BUDGET and Aforologito
3. It would be nice if the sum of the percentages of the categories is always 100% (in my case its 101%) 
4. UPDATE 05/09: I realized that all my card payments ( payment from my Bank account to repay my credit card balance) are erroneously categorized as "Fashion and Beauty"...

![aforologito](https://user-images.githubusercontent.com/107864092/187441682-f5af3736-d5bb-466e-8843-8a19a666b582.png)
![budget page displays isurance pansion transaction](https://user-images.githubusercontent.com/107864092/187441687-d1e24fce-e2de-4639-a7bc-e529b3e33a47.png)
![transaction categorized as Insuranse-pension](https://user-images.githubusercontent.com/107864092/187441692-38c4227c-12a9-4020-aae8-dd382b43a5c0.png)

**Comment by chris-iliopoulos** [comment]
About the points above:
1. We will have to see it in more depth and then come back with more details and an explanation, because credit card transactions are not handled in the same way as account/debit card transactions which have clearer categories.
2. About the correlation between the budget and the tax categories, we will check to see if there's a mapping between them but the truth is that the budget categories come from our analytics system and the tax deduction categories are fixed based on the government paper that the banks use.
3. The sum is always rounded up so there's no decimals, it's the same way the banks do it (checked mine).
4. See no.1 for more info.

**Comment by chris-iliopoulos** [comment]
Closing this issue because all points have been clarified and the credit card handling implementation, which will solve no.1, is already underway.
