### ISSUE TITLE
Update the transaction category

### ISSUE THREAD

**Issue by nikosdouv** [squaredev-io/GFM-UAT#95]
From transactions page i select an older transaction classified in OTHER category, select to assign a new category, press save,  waiting 2-3 seconds, then a loader and then the system takes me to the top of the transaction page.
1. The transaction category was not updated 
2. I had to scroll down again to locate the transaction in order to verify if the change of category was successful 
I would expect after a successful update the user would see again the detailed page (updated with the new category code or not)

**Comment by chris-iliopoulos** [comment]
- The first point is something that we cannot reproduce. It seems to e working fine with the only thing missing being a Loader, which is an open issue already.
- The second point is something that needs discussion because we already have 2 different opinions on it. @ksiabani & @geikosipentakis pls give your feedback.
   Do we want the transaction details to open in a modal (my personal preference) so the transactions list in the background stays put every time and doesn't create the problem above (scrolling to top)? Or do we want to keep it as a different page that the user keeps seeing after the category update?

**Comment by chris-iliopoulos** [comment]
In this issue the implementation will contain the fix for the 2nd point along with the enhancement of the transactions categories labels/tags which is contained as a proposal in issue: https://github.com/squaredev-io/GFM-UAT/issues/99

**Comment by chris-iliopoulos** [comment]
@geikosipentakis we will need the transactions categories labels (https://www.figma.com/file/hl3biSsMK3Z8PlsCa8rLZs/GFM?node-id=595%3A543) also for mobile view

**Comment by chris-iliopoulos** [comment]
The enhancement about the categories labels will be tracked here: https://github.com/squaredev-io/GFM-UAT/issues/120
