### ISSUE TITLE
Need a UX thing to let the user know that the new bank info (after connecting) are being processed.

### ISSUE THREAD

**Issue by chris-iliopoulos** [squaredev-io/GFM-UAT#99]

**Comment by geikosipentakis** [comment]
Since the functionality of transaction categorization exists, I think we can take advantage of that in creating labels in the transactions page for each one separately in the table. In that way we can engage the user to use this function. Check frame "Transactions"

https://www.figma.com/file/hl3biSsMK3Z8PlsCa8rLZs/GFM?node-id=595%3A543

In the transaction page I have changed some button apperances, so that the user can identify the difference between "Back" and "Save and Close" buttons. Check frames Transaction Page 1", "Transaction Page modal 1", "Transaction Page modal 2"

After discussing with Nikos, I think that returning to the transactions page will be the best case scenario, but we must have a toast message prompt that disappears after 2 or 3 seconds (the user can close it if he wants). That way the user is aware if the changes he made are completed or not. Check frame "Transactions final"

**Comment by chris-iliopoulos** [comment]
Since the Transactions Final mockup is the only relevant UX we could use for the case of this issue, I will keep this as a guide and probably open another issue for the Transactions categories labels. That being said the process running in the background is asynchronous meaning the client (GFM) doesn't and can't know when it will end and at this stage if it's been successfully completed or not (in regards to the red and green toast msgs). So for now I think we only use the blue one and when the app refreshes and sees that it receives the required data the toast msg could disappear.

**Comment by chris-iliopoulos** [comment]
This issue will only contain the half of the problem, which is to let the user know that a background process is running. For the transactions categories the UX will be implemented in the issue: https://github.com/squaredev-io/GFM-UAT/issues/95
